NormalRepair of slng-discovery rule 4973
Normal repair had to be used due to SniperPrettyBug:
spoon.SpoonException: Unexpected state: Token writer is muted after scanning